(()=>{'use strict';const E=window.WellEngine,Plus=window.WellPlus,Ico=window.BhaIcons,$=id=>document.getElementById(id),fmt=(x,n=1)=>Number.isFinite(x)?x.toLocaleString('fr-FR',{minimumFractionDigits:n,maximumFractionDigits:n}):'—',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const demoRef=`md,inc,azi\n0,0,0\n500,0,0\n950,7,30\n1300,23,37\n1650,42,48\n2000,60,58\n2350,76,65\n2700,86,69\n3050,91,70\n3400,90,70`;
const demoOff=`md,inc,azi\n0,0,0\n500,0,0\n950,6,23\n1300,19,33\n1650,36,46\n2000,55,54\n2350,74,62\n2700,86,66\n3050,90,68\n3400,90,68`;
const demoSide=`md,inc,azi\n0,0,0\n500,0,0\n950,7,30\n1300,23,37\n1650,42,48\n2000,60,58\n2350,78,88\n2700,89,103\n3050,90,108\n3400,90,110`;
const demoBha=[{name:'Trépan PDC',length:0.45,od:0.216,id:0.025,mass:64},{name:'PDM 6¾"',length:9.4,od:0.172,id:0.075,mass:122},{name:'NMDC / MWD',length:25,od:0.172,id:0.07,mass:105},{name:'Stabilizer near-bit',length:1.5,od:0.208,id:0.07,mass:132},{name:'Drill collars',length:135,od:0.172,id:0.075,mass:120},{name:'HWDP',length:300,od:0.127,id:0.075,mass:54},{name:'Drill pipe 5"',length:3200,od:0.127,id:0.108,mass:30}];
let state={refcsv:demoRef,offcsv:demoOff,offnorth:45,offeast:-20,offBnorth:-33,offBeast:65,offBcsv:demoOff,sidecsv:demoSide,srefE:14,soffE:16,srefV:4,soffV:5,caseId:"near",mu:.25,mud:1200,steel:7850,bitforce:0,hookref:0,hookcap:0,rref:.108,roff:.108,sref:8,soff:10,bha:demoBha.map(b=>({...b})),select:7,focus:"OFFSET A"};let derived={},view={yaw:0.75,pitch:0.39,zoom:1,drag:false,lastX:0,lastY:0,hotspots:[]};let currentPage='overview';
const pages=['overview','trajectory','collision','td','bha','report'];
function nav(page){currentPage=page;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('crumb').textContent=({overview:'VUE PUITS 3D',trajectory:'TRAJECTOIRES',collision:'ANTICOLLISION',td:'TORQUE & DRAG',bha:'DRILLSTRING & BHA',report:'RAPPORT TECHNIQUE'})[page];render();}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));
function inputValues(){for(let k of ['offnorth','offeast','mu','mud','steel','bitforce','hookref','hookcap','rref','roff','sref','soff','srefE','soffE','srefV','soffV','offBnorth','offBeast']){let id=({mu:'friction',mud:'mud',steel:'steel',bitforce:'bitforce',hookref:'hookref',hookcap:'hookcap',rref:'rref',roff:'roff',sref:'sref',soff:'soff',srefE:'srefE',soffE:'soffE',srefV:'srefV',soffV:'soffV',offnorth:'offnorth',offeast:'offeast',offBnorth:'offBnorth',offBeast:'offBeast'})[k];state[k]=Number($(id).value);}state.refcsv=$('reftext').value;state.offcsv=$('offtext').value;state.offBcsv=$('offBtext').value;state.sidecsv=$('sidetext').value;}
function syncInputs(){for(let k of ['offnorth','offeast','mu','mud','steel','bitforce','hookref','hookcap','rref','roff','sref','soff','srefE','soffE','srefV','soffV','offBnorth','offBeast']){let id=k==='mu'?'friction':k;$(id).value=state[k];}$('reftext').value=state.refcsv;$('offtext').value=state.offcsv;$('offBtext').value=state.offBcsv;$('sidetext').value=state.sidecsv;$('acfocus').value=state.focus||'OFFSET A';}
function compute(){for(const k of ['sref','srefE','srefV','soff','soffE','soffV','rref','roff'])if(!Number.isFinite(state[k])||state[k]<0||state[k]>500)throw Error('Incertitudes/rayons hypothétiques : valeur attendue entre 0 et 500 m');let ref=E.survey(E.parseCSV(state.refcsv)),base=E.survey(E.parseCSV(state.offcsv));let off=base.map(p=>({...p,n:p.n+state.offnorth,e:p.e+state.offeast}));let bha=E.normalizeBha(state.bha);if(bha.totalLength<ref.at(-1).md)throw Error('Le train de forage doit couvrir toute la MD du bit : compléter la longueur de DP dans BHA.');let baseB=E.survey(E.parseCSV(state.offBcsv));let offB=baseB.map(p=>({...p,n:p.n+state.offBnorth,e:p.e+state.offBeast}));let side=E.survey(E.parseCSV(state.sidecsv));if(side.filter(p=>p.md>=2000).length<2)throw Error('Sidetrack : au moins 2 stations MD >= 2000 m requises.');let parent=ref.find(x=>x.md===2000),sideAnchor=side.find(x=>x.md===2000);if(!parent||!sideAnchor)throw Error('Exercice sidetrack : MD 2000 doit être une station du parent et du sidetrack.');side=side.map(p=>({...p,n:p.n+parent.n-sideAnchor.n,e:p.e+parent.e-sideAnchor.e,tvd:p.tvd+parent.tvd-sideAnchor.tvd}));
let acA=E.anticollision(ref,off,state.sref,state.soff,state.rref,state.roff).map(r=>({...r,well:'OFFSET A'}));let acB=E.anticollision(ref,offB,state.sref,state.soff,state.rref,state.roff).map(r=>({...r,well:'OFFSET B'}));let acSide=E.anticollision(ref,side.filter(p=>p.md>=2000),state.sref,state.soff,state.rref,state.roff).filter(r=>r.md>2150).map(r=>({...r,well:'SIDETRACK'}));let ac=[...acA,...acB,...acSide];let td={};for(let mode of ['pooh','rih','static'])td[mode]=E.td(ref,state.bha,{mu:state.mu,mud:state.mud,steel:state.steel,bitForce:state.bitforce*1000,mode});derived={ref,off,offB,side,bha,ac,td};state.select=Math.min(state.select,ref.length-1);return derived;}
function update(from){try{inputValues();compute();$('survey-error').textContent='';$('off-error').textContent='';$('td-error').textContent='';$('bha-error').textContent='';render();return true;}catch(e){$(from||'survey-error').textContent=e.message;return false;}}
function setText(id,s){$(id).textContent=s;}
function render(){if(!derived.ref)return;let {ref,off,offB,side,bha,ac,td}=derived,bit=ref.at(-1),smallest=ac.reduce((a,b)=>a.center<b.center?a:b);setText('k-md',fmt(bit.md,0));setText('k-tvd',fmt(bit.tvd,1));setText('k-dls',fmt(Math.max(...ref.map(x=>x.dls)),2));setText('k-sep',fmt(smallest.center,1));$('station-slider').max=ref.length-1;$('station-slider').value=state.select;$('ac-depthslider').max=ref.length-1;$('ac-depthslider').value=state.select;setText('ac-selected-depth',fmt(ref[state.select].md,0)+' mMD');let st=ref[state.select];setText('station-name','STATION '+state.select);setText('st-md',fmt(st.md,1)+' m');setText('st-angles',fmt(st.inc,1)+'° / '+fmt(st.azi,1)+'°');setText('st-coord',fmt(st.n,0)+' / '+fmt(st.e,0)+' / '+fmt(st.tvd,0)+' m');setText('st-dls',fmt(st.dls,2)+' °/30m');$('qc').innerHTML=`<div><span>●</span> ${ref.length} stations survey chargées</div><div><span>●</span> ${bha.elements.length} composants géométriques</div><div><span>●</span> ${off.length} stations offset chargées</div><div class="warn"><span>●</span> Covariance et modèle anticollision indisponibles</div><div class="warn"><span>●</span> T&D : modèle préliminaire, pas de limites certifiées</div>`;
setText('ac-min',fmt(smallest.center,2));setText('ac-depth',fmt(smallest.md,0));setText('td-pu',fmt(td.pooh.hookload/1000,1));setText('td-so',fmt(td.rih.hookload/1000,1));setText('td-st',fmt(td.static.hookload/1000,1));setText('td-ref-result',state.hookref?fmt(state.hookref,1)+' kN':'Non fourni');setText('td-cap-result',state.hookcap?fmt(state.hookcap,1)+' kN · valeur saisie':'Non fournie');setText('td-elements-result',String(bha.elements.length));let sr=td.pooh.rows.reduce((v,p)=>Math.abs(p.md-ref[state.select].md)<Math.abs(v.md-ref[state.select].md)?p:v);setText('td-sectionload',Plus.chooseSegment(ref[state.select].md)+' · '+fmt(sr.axial/1000,0)+' kN (axial local)');setText('bha-len',fmt(bha.totalLength,1));setText('bha-mass',fmt(bha.elements.reduce((s,x)=>s+x.mass*x.length,0)/1000,1));
$('surveytable').querySelector('tbody').innerHTML=ref.map((p,i)=>`<tr><td>${fmt(p.md,0)}</td><td>${fmt(p.inc,1)}</td><td>${fmt(p.azi,1)}</td><td>${fmt(p.tvd,1)}</td><td>${fmt(p.n,1)}</td><td>${fmt(p.e,1)}</td><td>${fmt(p.dls,2)}</td></tr>`).join('');
$('actable').querySelector('tbody').innerHTML=ac.map(r=>`<tr><td>${esc(r.well)}</td><td>${fmt(r.md,0)}</td><td>${fmt(r.offset.md,0)}</td><td>${fmt(r.center,1)}</td><td>${fmt(r.physicalGap,1)}</td></tr>`).join('');
renderScene();renderScene('acscene');renderTDScene();renderACCross();renderACPlan();renderSectionStrip();renderPlan();renderXY('trajectoryplot',[{label:'TVD',col:'#4bd8c0',rows:ref.map(p=>[p.md,p.tvd])},{label:'North',col:'#f3a25d',rows:ref.map(p=>[p.md,p.n])}],{x:'MD (m)',y:'TVD / North (m)'});renderXY('acplot',[{label:'Centres',col:'#48d7c1',rows:ac.map(p=>[p.md,p.center])},{label:'Gap physique nominal',col:'#f7a957',rows:ac.map(p=>[p.md,p.physicalGap])}],{x:'MD référence (m)',y:'Distance (m)'});renderXY('tdplot',[{label:'Pickup',col:'#f7a957',rows:td.pooh.rows.map(p=>[p.md,p.axial/1000])},{label:'Slackoff',col:'#6aa8f8',rows:td.rih.rows.map(p=>[p.md,p.axial/1000])},{label:'Static',col:'#48d7c1',rows:td.static.rows.map(p=>[p.md,p.axial/1000])}],{x:'MD (m)',y:'Force axiale (kN)'});renderBha();renderReport();}
function canvas2(id){let c=$(id),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);return [c,ctx]}
function renderXY(id,series,opt){let [c,g]=canvas2(id),W=c.width,H=c.height,ml=58,mr=17,mt=33,mb=35,all=series.flatMap(s=>s.rows).filter(p=>p.every(Number.isFinite));if(!all.length)return;let x0=Math.min(...all.map(a=>a[0])),x1=Math.max(...all.map(a=>a[0]));let y0=Math.min(...all.map(a=>a[1])),y1=Math.max(...all.map(a=>a[1]));if(y1===y0){y0-=1;y1+=1}let pad=(y1-y0)*.08;y0-=pad;y1+=pad;let X=x=>ml+(x-x0)/(x1-x0||1)*(W-ml-mr),Y=y=>H-mb-(y-y0)/(y1-y0)*(H-mt-mb);g.font='12px Segoe UI';g.lineWidth=1;g.strokeStyle='#284055';g.fillStyle='#86a3b5';for(let j=0;j<5;j++){let y=mt+j*(H-mt-mb)/4;g.beginPath();g.moveTo(ml,y);g.lineTo(W-mr,y);g.stroke();g.fillText(fmt(y1-j*(y1-y0)/4,0),7,y+4);}for(let j=0;j<5;j++){let x=ml+j*(W-ml-mr)/4;g.fillText(fmt(x0+j*(x1-x0)/4,0),x-8,H-16);}g.fillStyle='#9fb6c7';g.fillText(opt.y,8,14);g.fillText(opt.x,W-90,H-9);
series.forEach((s,i)=>{g.strokeStyle=s.col;g.lineWidth=2.6;g.beginPath();s.rows.forEach((p,j)=>j?g.lineTo(X(p[0]),Y(p[1])):g.moveTo(X(p[0]),Y(p[1])));g.stroke();g.fillStyle=s.col;g.fillRect(ml+i*160,21,12,3);g.fillStyle='#a6c0d3';g.fillText(s.label,ml+17+i*160,26);});}
function renderPlan(){let [c,g]=canvas2('plan'),{ref,off}=derived,pts=[...ref,...off];let a=Math.min(...pts.map(p=>p.e)),b=Math.max(...pts.map(p=>p.e)),d=Math.min(...pts.map(p=>p.n)),e=Math.max(...pts.map(p=>p.n)),scale=Math.min((c.width-55)/(b-a||1),(c.height-30)/(e-d||1));let X=p=>30+(p.e-a)*scale,Y=p=>c.height-15-(p.n-d)*scale;g.strokeStyle='#1e3548';for(let j=0;j<6;j++){g.beginPath();g.moveTo(j*c.width/5,0);g.lineTo(j*c.width/5,c.height);g.stroke()}for(let [rows,col] of [[ref,'#48d7c1'],[off,'#f7a957']]){g.beginPath();rows.forEach((p,i)=>i?g.lineTo(X(p),Y(p)):g.moveTo(X(p),Y(p)));g.lineWidth=3;g.strokeStyle=col;g.stroke();}let p=ref[state.select];g.fillStyle='#fff';g.beginPath();g.arc(X(p),Y(p),5,0,Math.PI*2);g.fill();g.fillStyle='#94aec1';g.font='12px Segoe UI';g.fillText('N ↑',8,13);g.fillText('E →',c.width-40,c.height-5);}
function renderScene(canvasId='scene'){let c=$(canvasId),g=c.getContext('2d'),W=c.width,H=c.height;g.clearRect(0,0,W,H);let {ref,off,offB,side,bha}=derived,detail=canvasId!=='scene',showOff=detail||$('showoffset').checked,showEll=detail||$('showellipses').checked,showBha=!detail&&$('showbha').checked,showSide=detail||$('showsidetrack').checked,showB=detail||$('showoffsetB').checked,pts=[...ref,...(showOff?off:[]),...(showSide?side:[]),...(showB?offB:[])];let min=Math.min(...pts.map(p=>p.n)),max=Math.max(...pts.map(p=>p.n)),minE=Math.min(...pts.map(p=>p.e)),maxE=Math.max(...pts.map(p=>p.e)),deep=Math.max(...pts.map(p=>p.tvd));let scale=Math.max(max-min,maxE-minE,deep*.90,500);let meanN=(min+max)/2,meanE=(minE+maxE)/2,meanZ=deep/2,yaw=view.yaw,pitch=view.pitch;
function rawP(p){let x=(p.e-meanE)/scale,y=(p.n-meanN)/scale,z=(p.tvd-meanZ)/scale;let xx=x*Math.cos(yaw)-y*Math.sin(yaw),yy=x*Math.sin(yaw)+y*Math.cos(yaw);let v=yy*Math.sin(pitch)+z*Math.cos(pitch),depth=yy*Math.cos(pitch)-z*Math.sin(pitch);let perspective=2.9/(3+depth*.35);return {x:xx*perspective,y:v*perspective,k:perspective};}let proj=pts.map(rawP),xlo=Math.min(...proj.map(p=>p.x)),xhi=Math.max(...proj.map(p=>p.x)),ylo=Math.min(...proj.map(p=>p.y)),yhi=Math.max(...proj.map(p=>p.y));let fit=Math.min((W-140)/(xhi-xlo||.5),(H-110)/(yhi-ylo||.5));function P(p){let q=rawP(p);return {x:W/2+(q.x-(xlo+xhi)/2)*fit*view.zoom,y:H/2+(q.y-(ylo+yhi)/2)*fit*view.zoom,k:q.k};}
function line(rows,col,width=3,dash=[]){g.beginPath();rows.forEach((p,i)=>{let q=P(p);i?g.lineTo(q.x,q.y):g.moveTo(q.x,q.y)});g.strokeStyle=col;g.lineWidth=width;g.setLineDash(dash);g.lineJoin='round';g.lineCap='round';g.stroke();g.setLineDash([]);}function dot(p,col,r=5){let q=P(p);g.fillStyle=col;g.beginPath();g.arc(q.x,q.y,r,0,Math.PI*2);g.fill();return q;}
for(let z=0;z<=deep;z+=Math.max(250,Math.ceil(deep/5/250)*250)){let rows=[{n:min-250,e:minE-250,tvd:z},{n:min-250,e:maxE+250,tvd:z},{n:max+250,e:maxE+250,tvd:z},{n:max+250,e:minE-250,tvd:z},{n:min-250,e:minE-250,tvd:z}];line(rows,'#183247',.75);let q=P(rows[0]);g.fillStyle='#557187';g.font='12px Segoe UI';g.fillText(Math.round(z)+' m',q.x-55,q.y+4);}line([{n:meanN,e:meanE,tvd:0},{n:meanN,e:meanE,tvd:deep}], '#29455a',1,[4,5]);if(showOff){line(off,'rgba(247,169,87,.17)',13);line(off,'#f7a957',3.5);}if(showB){line(offB,'rgba(106,168,248,.16)',11);line(offB,'#6aa8f8',3.1);}if(showSide){line(side.slice(5),'rgba(198,168,255,.19)',13);line(side.slice(5),'#c6a8ff',3.4);let kop=P(side.find(p=>p.md===2000));g.fillStyle='#c6a8ff';g.font='bold 12px Segoe UI';g.fillText('SIDETRACK KOP',kop.x+7,kop.y-8);}
line(ref,'rgba(72,215,193,.14)',17);line(ref,'#48d7c1',4.2);if(showBha){let j=Math.max(0,ref.length-2);line(ref.slice(j),'#6aa8f8',9);dot(ref.at(-1),'#fff',5)}
if(showEll){let idxs=detail?[5,6,7,8,9]:[5,7,9];for(let idx of idxs.filter(i=>i<ref.length)){
let targets=[{p:ref[idx],sig:[state.sref,state.srefE,state.srefV],c:'#b49bff'},...(showOff?[{p:off[Math.min(idx,off.length-1)],sig:[state.soff,state.soffE,state.soffV],c:'#f7a957'}]:[]),...(showB?[{p:offB[Math.min(idx,offB.length-1)],sig:[state.soff,state.soffE,state.soffV],c:'#6aa8f8'}]:[]),...(showSide&&idx>=5?[{p:side[Math.min(idx,side.length-1)],sig:[state.soff,state.soffE,state.soffV],c:'#c6a8ff'}]:[])];
for(let target of targets){let model=Plus.ellipse(target.p,target.sig,2),a=model.angle,ring=Array.from({length:41},(_,j)=>{let t=j/40*Math.PI*2,x=model.rx*Math.cos(t),y=model.ry*Math.sin(t),xx=x*Math.cos(a)-y*Math.sin(a),yy=x*Math.sin(a)+y*Math.cos(a);return {n:target.p.n+model.right[0]*xx+model.up[0]*yy,e:target.p.e+model.right[1]*xx+model.up[1]*yy,tvd:target.p.tvd+model.right[2]*xx+model.up[2]*yy}});line(ring,target.c,detail?1.7:1.2,[4,3]);}}
}
let q=dot(ref[state.select],'#fff',6);g.fillStyle='#b9e5dd';g.font='bold 14px Segoe UI';g.fillText('MD '+fmt(ref[state.select].md,0)+' m',q.x+12,q.y-8);let end=P(ref.at(-1));g.fillStyle='#48d7c1';g.font='bold 13px Segoe UI';g.fillText('BIT / TD',end.x+8,end.y+22);g.fillStyle='#5e7c92';g.font='12px Segoe UI';g.fillText('3D PROJECTION · 2σ INPUTS ONLY / NOT ISCWSA · DEMO',17,H-15);
if(!detail)view.hotspots=ref.map((p,i)=>({i,...P(p)}));}
function renderACCross(){let [c,g]=canvas2('accross'),{ref,ac}=derived,p=ref[state.select];let candidates=ac.filter(r=>r.md===p.md&&r.well===state.focus);let entries=[{name:'REFERENCE',p,offset:{x:0,y:0},sig:[state.sref,state.srefE,state.srefV],color:'#48d7c1'}];let colors={'OFFSET A':'#f7a957','OFFSET B':'#6aa8f8','SIDETRACK':'#c6a8ff'};candidates.forEach(r=>entries.push({name:r.well,p:r.offset,offset:Plus.transverseOffset(p,r.offset),sig:[state.soff,state.soffE,state.soffV],color:colors[r.well]}));
let models=entries.map(x=>({...x,model:Plus.ellipse(p,x.sig,2)}));let span=Math.max(32,...models.map(x=>Math.hypot(x.offset.x,x.offset.y)+Math.max(x.model.rx,x.model.ry)*1.5));let scale=Math.min((c.width-125)/(span*2),(c.height-82)/(span*2)),X=x=>c.width/2+x*scale,Y=y=>c.height/2-y*scale;
g.fillStyle='#829eaf';g.font='12px Segoe UI';g.fillText('PLAN TRANSVERSE / LOCAL RIGHT – HIGHSIDE',16,23);g.fillText('x = droite locale →',c.width-165,c.height-12);g.fillText('↑ côté highside',16,c.height-12);
g.strokeStyle='#2f475b';g.lineWidth=1;g.setLineDash([4,5]);g.beginPath();g.moveTo(c.width/2,32);g.lineTo(c.width/2,c.height-25);g.moveTo(35,c.height/2);g.lineTo(c.width-35,c.height/2);g.stroke();g.setLineDash([]);
models.forEach(entry=>{let m=entry.model,x=X(entry.offset.x),y=Y(entry.offset.y);g.beginPath();g.ellipse(x,y,Math.max(1,m.rx*scale),Math.max(1,m.ry*scale),-m.angle,0,Math.PI*2);g.fillStyle=entry.color+'12';g.fill();g.strokeStyle=entry.color;g.lineWidth=2.5;g.stroke();g.beginPath();g.arc(x,y,4,0,2*Math.PI);g.fillStyle=entry.color;g.fill();g.fillStyle='#d6eaf4';g.font='bold 12px Segoe UI';g.fillText(entry.name,x+9,y-9);});
if(models.length>1){let s=models[1];g.strokeStyle='#f8d49a';g.setLineDash([3,4]);g.beginPath();g.moveTo(X(0),Y(0));g.lineTo(X(s.offset.x),Y(s.offset.y));g.stroke();g.setLineDash([]);g.fillStyle='#acc6d3';g.font='11px Segoe UI';g.fillText('Écart transverse projeté '+fmt(Math.hypot(s.offset.x,s.offset.y),1)+' m',17,42)}
if(p.md<=2150&&state.focus==='SIDETRACK'){g.fillStyle='#ffc17e';g.fillText('Sidetrack : trou commun avant KOP · non comparé comme puits distinct',16,c.height-36);}g.fillStyle='#86a1b3';g.font='10px Segoe UI';g.fillText('2σ HYPOTHÉTIQUES · N/E/TVD INDÉPENDANTS · SANS MODÈLE ISCWSA',14,c.height-52);
}
function renderACPlan(){let [c,g]=canvas2('acplan'),{ref,off,offB,side}=derived,rows=[...ref,...off,...offB,...side],minE=Math.min(...rows.map(p=>p.e)),maxE=Math.max(...rows.map(p=>p.e)),minN=Math.min(...rows.map(p=>p.n)),maxN=Math.max(...rows.map(p=>p.n)),rangeE=maxE-minE||1,rangeN=maxN-minN||1,scale=Math.min((c.width-110)/rangeE,(c.height-92)/rangeN),dx=(c.width-rangeE*scale)/2,dy=(c.height-rangeN*scale)/2,X=p=>dx+(p.e-minE)*scale,Y=p=>c.height-dy-(p.n-minN)*scale;
g.strokeStyle='#213a4b';g.lineWidth=1;for(let j=1;j<7;j++){let x=j*c.width/7,y=j*c.height/7;g.beginPath();g.moveTo(x,0);g.lineTo(x,c.height);g.moveTo(0,y);g.lineTo(c.width,y);g.stroke()}
for(let [items,color,w] of [[ref,'#48d7c1',3.5],[off,'#f7a957',2.5],[offB,'#6aa8f8',2.5],[side.slice(5),'#c6a8ff',3]]){g.beginPath();items.forEach((p,i)=>i?g.lineTo(X(p),Y(p)):g.moveTo(X(p),Y(p)));g.strokeStyle=color;g.lineWidth=w;g.stroke();let last=items.at(-1);g.fillStyle=color;g.font='bold 11px Segoe UI';g.fillText(({ '#48d7c1':'REFERENCE','#f7a957':'OFFSET A','#6aa8f8':'OFFSET B','#c6a8ff':'SIDETRACK'})[color],X(last)+6,Y(last)-7)}let selected=ref[state.select];g.beginPath();g.arc(X(selected),Y(selected),5,0,2*Math.PI);g.fillStyle='#fff';g.fill();let kop=side.find(p=>p.md===2000);g.beginPath();g.arc(X(kop),Y(kop),5,0,2*Math.PI);g.fillStyle='#c6a8ff';g.fill();g.font='11px Segoe UI';g.fillText('KOP',X(kop)+7,Y(kop)-7);g.fillStyle='#acc0d2';g.fillText('N ↑',15,17);g.fillText('E →',c.width-48,c.height-10);}
function renderTDScene(){let [c,g]=canvas2('tdscene'),{ref,td}=derived,W=c.width,H=c.height,depth=Math.max(...ref.map(p=>p.tvd)),extent=Math.max(depth,...ref.map(p=>Math.hypot(p.n,p.e)));let az=view.yaw,co=Math.cos(az),si=Math.sin(az),p={x:ref.map(q=>q.e*co-q.n*si),y:ref.map(q=>q.e*si+q.n*co)};let px=p.x.map((v,i)=>v*.78),py=p.y.map((v,i)=>p.y[i]*.22+ref[i].tvd*.7),minX=Math.min(...px),maxX=Math.max(...px),minY=Math.min(...py),maxY=Math.max(...py),scale=Math.min((W-200)/(maxX-minX||1),(H-70)/(maxY-minY||1)),X=i=>90+(px[i]-minX)*scale,Y=i=>38+(py[i]-minY)*scale;
let colorList=['#6aa8f8','#38dcc0','#f7a957','#92b5ff','#c6a8ff','#4adb9c'],segmentId=md=>md<500?0:md<950?1:md<2000?2:md<2350?3:md<3050?4:5;
for(let i=1;i<ref.length;i++){let section=segmentId((ref[i-1].md+ref[i].md)/2);g.beginPath();g.moveTo(X(i-1),Y(i-1));g.lineTo(X(i),Y(i));g.lineWidth=11;g.strokeStyle=colorList[section]+'27';g.stroke();g.lineWidth=4.5;g.strokeStyle=colorList[section];g.stroke();}
ref.forEach((p,i)=>{let r=td.pooh.rows.reduce((v,q)=>Math.abs(q.md-p.md)<Math.abs(v.md-p.md)?q:v),v=Math.max(0,r.axial/1000),len=10+Math.min(36,v/10),y=Y(i);g.strokeStyle='#d5ac6b';g.lineWidth=1.5;g.beginPath();g.moveTo(X(i),y);g.lineTo(X(i)+len,y-10);g.stroke();if(i===state.select){g.beginPath();g.arc(X(i),y,7,0,Math.PI*2);g.fillStyle='#fff';g.fill();g.font='bold 12px Segoe UI';g.fillText('MD '+fmt(p.md,0)+' · '+fmt(v,0)+' kN',X(i)+12,y-16);}});
g.fillStyle='#b3c8d4';g.font='11px Segoe UI';g.fillText('Surface / vertical section',15,21);g.fillText('TVD ↓',16,H-16);g.fillText('TD / lateral section',W-150,H-16);g.fillStyle='#8ab4c8';g.fillText('T&D 3D SCHÉMATIQUE : FORCE AXIALE · PAS DE FORCE DE CONTACT STIFF-STRING',W-490,21);}
function renderSectionStrip(){const bands=[['VERTICAL','0–500',250],['KOP / BUILD','500–950',725],['BUILD','950–2000',1450],['TANGENT / HOLD','2000–2350',2175],['LANDING','2350–3050',2700],['LATERAL','3050–3400',3225]],selected=derived.ref[state.select].md;
$('sectionstrip').innerHTML=bands.map(([title,range,md],i)=>{let p=derived.td.pooh.rows.reduce((v,q)=>Math.abs(q.md-md)<Math.abs(v.md-md)?q:v);return `<button class="sectiontile ${((selected<500?0:selected<950?1:selected<2000?2:selected<2350?3:selected<3050?4:5)===i)?'active':''}" data-section="${i}" title="Sélection de section – valeur du modèle axial simplifié"><span>${title}</span><strong>${fmt(p.axial/1000,0)} kN</strong><small>${range} mMD<br>Pickup local</small></button>`}).join('');$('sectionstrip').querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{const target=[250,725,1450,2175,2700,3225][+b.dataset.section];let best=derived.ref.reduce((v,p,i)=>Math.abs(p.md-target)<Math.abs(derived.ref[v].md-target)?i:v,0);state.select=best;render()})}

function renderBha(){
$('bhaicons').innerHTML=bhaSummary(derived.bha.elements);let [c,g]=canvas2('bhaplot'),{bha}=derived,els=bha.elements,W=c.width,H=c.height;g.font='11px Segoe UI';g.fillStyle='#9eb7c7';g.fillText('SURFACE',20,17);g.fillText('BIT',20,H-8);g.lineWidth=2;g.strokeStyle='#2d536a';g.beginPath();g.moveTo(95,30);g.lineTo(95,H-25);g.stroke();let slot=(H-69)/els.length;els.slice().reverse().forEach((b,i)=>{let mid=34+(i+.5)*slot,hh=Math.min(33,slot*.72),width=10+b.od*103;g.fillStyle=['#467ba3','#6098b2','#cf8497','#f2b96c','#b290ed','#6498c5','#52cbb8'][i%7];g.fillRect(95-width/2,mid-hh/2,width,hh);g.strokeStyle='#4c697f';g.beginPath();g.moveTo(115,mid);g.lineTo(161,mid);g.stroke();g.fillStyle='#acc2d3';g.font='11px Segoe UI';g.fillText(b.name+'  ·  '+fmt(b.length,1)+' m',168,mid+4);});g.fillStyle='#7899ad';g.font='10px Segoe UI';g.fillText('Position schématique — longueurs non à l’échelle',20,H-27);}

function bhaSummary(elements){return elements.slice(0,11).map(b=>{let tp=Ico.typeOf(b.name);return `<div class="bhacomponent" title="${esc(b.name)} · géométrie réelle à saisir"><div>${Ico.svg(tp)}</div><b>${esc(b.name)}</b></div>`}).join('')}
function renderToolGallery(){$('toolgallery').innerHTML=Ico.library.map((tool,i)=>`<button class="toolcard" data-tool="${i}" title="Insérer ${esc(tool.label)} dans la composition (propriétés synthétiques à modifier)">${Ico.svg(tool.type)}<strong>${esc(tool.label)}</strong><small>${esc(tool.sub)}</small></button>`).join('');$('toolgallery').querySelectorAll('[data-tool]').forEach(btn=>btn.onclick=()=>{let t=Ico.library[+btn.dataset.tool];let ix=state.bha.findIndex(b=>Ico.typeOf(b.name)==='dp');if(ix<0)ix=state.bha.length;state.bha.splice(ix,0,{name:t.name,length:t.length,od:t.od,id:t.id,mass:t.mass});renderBhaTable();update('bha-error');$('bhatable').scrollIntoView({behavior:'smooth',block:'center'});});}
function renderReport(){let {ref,off,offB,side,bha,ac,td}=derived,min=ac.reduce((a,b)=>a.center<b.center?a:b);$('reportbody').innerHTML=`<section><h3>1 · Identification / qualification</h3><p>WellScope Engineering ALPHA 0.3. Cas indépendant synthétique ; usage : formation, revue de données et pré-analyse exploratoire. Aucun résultat certifié.</p></section><section><h3>2 · Trajectoire</h3><p>${ref.length} surveys · MD finale ${fmt(ref.at(-1).md,1)} m · TVD finale ${fmt(ref.at(-1).tvd,1)} m · méthode minimum curvature · repère local N/E/TVD sans géodésie.</p></section><section><h3>3 · Offset / anticollision</h3><p>${off.length} stations offset ; distance minimale échantillonnée ${fmt(min.center,2)} m au MD réf. ${fmt(min.md,0)} m. Les rayons de trou sont saisis ; les ellipses 2σ proviennent uniquement de variances diagonales N/E/TVD supposées, sans corrélations ni propagation instrumentale. Aucun gap d’enveloppe, facteur de séparation, probabilité de collision ou critère d’acceptation calculé.</p></section><section><h3>4 · Torque &amp; Drag</h3><p>Soft-string screening (pas ABIS) ; hookload pickup ${fmt(td.pooh.hookload/1000,1)} kN · slackoff ${fmt(td.rih.hookload/1000,1)} kN · statique ${fmt(td.static.hookload/1000,1)} kN. Coefficient µ ${fmt(state.mu,2)}, boue ${fmt(state.mud,0)} kg/m³. Aucun seuil d'approbation.</p></section><section><h3>5 · Train de forage</h3><p>${bha.elements.length} composants ; longueur cumulée ${fmt(bha.totalLength,1)} m. OD/ID/masse linéique saisies ; composants utilisés pour la masse et le poids apparent, pas pour un solveur flexible 3D.</p></section><section><h3>6 · Limitations explicites</h3><p>Absents : géoréférencement commun validé, error models ISCWSA, covariance et corrélations, contrôle anticollision réel ; stiff-string, stabilisateurs et contact réaliste, flambage, couple de surface, limites connexions et hookload admissible, dynamique et harmoniques, BHA directional response, étalonnage terrain et comparaison aux solveurs de référence.</p></section>`;}
function download(name,text,mime='text/plain'){let blob=new Blob([text],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('btnsave').onclick=$('exportjson').onclick=()=>download('wellscope_case_ALPHA.json',JSON.stringify(state,null,2),'application/json');$('btnload').onclick=()=>$('projectfile').click();$('projectfile').onchange=async ev=>{try{let o=JSON.parse(await ev.target.files[0].text());if(!o.refcsv||!o.offcsv||!Array.isArray(o.bha))throw Error('Format de cas invalide');state={...state,...o};syncInputs();compute();render();}catch(e){alert('Import : '+e.message)}ev.target.value=''};
$('applyref').onclick=()=>update('survey-error');$('applymultioff').onclick=()=>update('off-error');$('applyoffset').onclick=()=>update('off-error');$('applytd').onclick=()=>update('td-error');$('acfocus').onchange=e=>{state.focus=e.target.value;renderACCross()};$('station-slider').oninput=$('ac-depthslider').oninput=e=>{state.select=+e.target.value;render()};for(let id of ['showoffset','showellipses','showbha','showsidetrack','showoffsetB'])$(id).onchange=renderScene;
function readFile(input,target){input.onchange=async e=>{try{$(target).value=await e.target.files[0].text();if(['offtext','offBtext','sidetext'].includes(target))update('off-error');else update('survey-error')}catch(x){alert(x.message)}e.target.value=''}}readFile($('refcsv'),'reftext');readFile($('offcsv'),'offtext');readFile($('offBfile'),'offBtext');readFile($('sidefile'),'sidetext');
$('exportcsv').onclick=()=>download('wellscope_survey_calculated.csv',['md,inc,azi,tvd,n,e,dls',...derived.ref.map(p=>['md','inc','azi','tvd','n','e','dls'].map(k=>p[k].toFixed(6)).join(','))].join('\n'),'text/csv');$('resetdemo').onclick=()=>{state.refcsv=demoRef;state.offcsv=demoOff;state.caseId='near';state.offnorth=45;state.offeast=-20;state.offBnorth=-33;state.offBeast=65;state.offBcsv=demoOff;state.sidecsv=demoSide;state.select=7;syncInputs();compute();render();};
function renderBhaTable(){let tb=$('bhatable').querySelector('tbody');tb.innerHTML=state.bha.map((b,i)=>`<tr data-i="${i}"><td><input class="widename" data-key="name" value="${esc(b.name)}"></td>${['length','od','id','mass'].map(k=>`<td><input data-key="${k}" type="number" step="any" value="${b[k]}"></td>`).join('')}<td><button class="del" data-del="${i}" aria-label="Supprimer">×</button></td></tr>`).join('');tb.querySelectorAll('[data-del]').forEach(btn=>btn.onclick=()=>{state.bha.splice(+btn.dataset.del,1);renderBhaTable();});}
$('addbha').onclick=()=>{state.bha.push({name:'Nouveau DP',length:100,od:.127,id:.105,mass:30});renderBhaTable()};$('applybha').onclick=()=>{let rows=[...$('bhatable').querySelectorAll('tbody tr')];state.bha=rows.map(tr=>Object.fromEntries([...tr.querySelectorAll('input')].map(x=>[x.dataset.key,x.dataset.key==='name'?x.value:Number(x.value)])));update('bha-error');};$('printreport').onclick=()=>{nav('report');window.print()};
for(const id of ['acscene']){let c3=$(id);c3.style.touchAction='none';c3.onpointerdown=e=>{view.drag=true;view.lastX=e.clientX;view.lastY=e.clientY;c3.setPointerCapture(e.pointerId)};c3.onpointermove=e=>{if(!view.drag)return;view.yaw+=(e.clientX-view.lastX)*.009;view.pitch=Math.max(-1.18,Math.min(1.18,view.pitch+(e.clientY-view.lastY)*.005));view.lastX=e.clientX;view.lastY=e.clientY;renderScene('scene');renderScene('acscene');renderTDScene();};c3.onpointerup=e=>{view.drag=false;c3.releasePointerCapture(e.pointerId)};c3.onwheel=e=>{e.preventDefault();view.zoom=Math.max(.45,Math.min(3,view.zoom*(e.deltaY>0?.91:1.09)));renderScene('scene');renderScene('acscene')}}
document.querySelectorAll('[data-case]').forEach(btn=>btn.onclick=()=>{state.caseId=btn.dataset.case;let presets={near:[45,-20],wide:[220,-180],intersection:[12,-5]};[state.offnorth,state.offeast]=presets[state.caseId];document.querySelectorAll('[data-case]').forEach(b=>b.classList.toggle('active',b===btn));syncInputs();compute();render()});
const c=$('scene');c.onpointerdown=e=>{view.drag=true;view.lastX=e.clientX;view.lastY=e.clientY;c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!view.drag)return;view.yaw+=(e.clientX-view.lastX)*.009;view.pitch=Math.max(-1.18,Math.min(1.18,view.pitch+(e.clientY-view.lastY)*.005));view.lastX=e.clientX;view.lastY=e.clientY;renderScene()};c.onpointerup=e=>{view.drag=false;c.releasePointerCapture(e.pointerId)};c.onwheel=e=>{e.preventDefault();view.zoom=Math.max(.45,Math.min(3,view.zoom*(e.deltaY>0?.91:1.09)));renderScene()};c.onclick=e=>{let r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height,b=view.hotspots.reduce((a,q)=>{let d=Math.hypot(x-q.x,y-q.y);return d<a.d?{d,i:q.i}:a},{d:30,i:-1});if(b.i>=0){state.select=b.i;render()}};
try{syncInputs();compute();renderBhaTable();renderToolGallery();render();}catch(e){console.error(e);$('survey-error').textContent=e.message;}
})();
