/* WellScope Engineering ALPHA — independent teaching / screening engine. No operational approval. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.WellEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const R=Math.PI/180,G=9.80665;
function finite(n,label){if(n===null||n===undefined||typeof n==='boolean'||String(n).trim()==='')throw Error(label+' is missing');n=Number(n);if(!Number.isFinite(n))throw Error(label+' must be numeric');return n;}
function survey(rows){if(!Array.isArray(rows)||rows.length<2)throw Error('At least two survey stations are required');const s=rows.map((q,i)=>({md:finite(q.md,'MD row '+i),inc:finite(q.inc,'INC row '+i),azi:finite(q.azi,'AZI row '+i)}));
for(let i=0;i<s.length;i++){let p=s[i];if(p.md<0||p.inc<0||p.inc>180||p.azi<0||p.azi>360)throw Error('Survey MD / inc / azi out of range at row '+(i+1));if(i&&p.md<=s[i-1].md)throw Error('Survey MD values must be strictly increasing');}
if(s[0].md!==0)throw Error('Survey must start at MD 0; explicit tie-in required otherwise');
const out=[{...s[0],n:0,e:0,tvd:s[0].md*Math.cos(s[0].inc*R),dls:0}];
for(let i=1;i<s.length;i++){let a=s[i-1],b=s[i],d=b.md-a.md,I1=a.inc*R,I2=b.inc*R,A1=a.azi*R,A2=b.azi*R;
let c=Math.cos(I1)*Math.cos(I2)+Math.sin(I1)*Math.sin(I2)*Math.cos(A2-A1);let beta=Math.acos(Math.max(-1,Math.min(1,c)));if(Math.PI-beta<1e-8)throw Error('Antipodal survey tangents are ambiguous');let rf=beta<1e-9?1:2*Math.tan(beta/2)/beta;let p=out[i-1];
out.push({...b,n:p.n+d/2*(Math.sin(I1)*Math.cos(A1)+Math.sin(I2)*Math.cos(A2))*rf,e:p.e+d/2*(Math.sin(I1)*Math.sin(A1)+Math.sin(I2)*Math.sin(A2))*rf,tvd:p.tvd+d/2*(Math.cos(I1)+Math.cos(I2))*rf,dls:beta/R/d*30});}
return out;}
function interp(st,md){if(md<=st[0].md)return {...st[0]};if(md>=st[st.length-1].md)return {...st[st.length-1]};let lo=0,hi=st.length-1;while(hi-lo>1){let j=(lo+hi)>>1;st[j].md<md?lo=j:hi=j;}let a=st[lo],b=st[hi],t=(md-a.md)/(b.md-a.md);return Object.fromEntries(['md','inc','azi','n','e','tvd','dls'].map(k=>[k,k==='azi'?(a.azi+(((b.azi-a.azi+540)%360)-180)*t+360)%360:a[k]+(b[k]-a[k])*t]));}
function dist3(a,b){return Math.hypot(a.n-b.n,a.e-b.e,a.tvd-b.tvd);}
function closestOnPolyline(p,stations){let best=null;for(let i=1;i<stations.length;i++){let a=stations[i-1],b=stations[i],dn=b.n-a.n,de=b.e-a.e,dz=b.tvd-a.tvd;let len=dn*dn+de*de+dz*dz;let t=len?Math.max(0,Math.min(1,((p.n-a.n)*dn+(p.e-a.e)*de+(p.tvd-a.tvd)*dz)/len)):0;let q={md:a.md+t*(b.md-a.md),n:a.n+t*dn,e:a.e+t*de,tvd:a.tvd+t*dz};let d=dist3(p,q);if(!best||d<best.distance)best={...q,distance:d};}return best;}
function anticollision(ref,offset,sigmaRef=0,sigmaOffset=0,rRef=0,rOffset=0){let rows=ref.map(p=>{let q=closestOnPolyline(p,offset);let d=q.distance;let assumedRadius=Math.hypot(sigmaRef,sigmaOffset);return {md:p.md,ref:p,offset:q,center:d,physicalGap:d-rRef-rOffset,assumedEnvelopeGap:d-rRef-rOffset-assumedRadius,uncertaintyRadius:assumedRadius};});return rows;}
function normalizeBha(bha){if(!bha||!bha.length)throw Error('The BHA cannot be empty');let sum=0;const rows=bha.map((b,i)=>{let name=String(b.name||'Component '+(i+1));let length=finite(b.length,name+' length'),od=finite(b.od,name+' OD'),id=finite(b.id,name+' ID'),mass=finite(b.mass,name+' kg/m');if(length<=0||od<=0||id<0||id>=od||mass<=0)throw Error('Invalid BHA component geometry: '+name);sum+=length;return {...b,name,length,od,id,mass,start:sum-length,end:sum}});return {elements:rows,totalLength:sum};}
function elementAtBottomDistance(bha,bottomDistance){for(let b of bha.elements)if(bottomDistance<b.end)return b;return bha.elements[bha.elements.length-1];}
function td(st,raw,settings){/* Soft-string screening: discrete resultant normal ~ |w sin(I)ds| + |T_bottom|*dogleg; ignores stiffness, torque-on-bit, hydrodynamic effects. */
let bha=normalizeBha(raw);const mu=finite(settings.mu,'friction'),mud=finite(settings.mud,'mud density'),rho=finite(settings.steel||7850,'steel density');if(mu<0||mu>1.5||mud<0||mud>=rho)throw Error('Invalid mud density or friction coefficient');const depth=settings.bitMD===undefined?st[st.length-1].md:finite(settings.bitMD,'Bit MD');if(depth<=0||depth>st.at(-1).md)throw Error('Bit MD outside survey domain');let depths=new Set([0,depth,...st.filter(p=>p.md<depth).map(p=>p.md),...bha.elements.flatMap(b=>[depth-b.start,depth-b.end]).filter(md=>md>0&&md<depth)]);st=[...depths].sort((a,b)=>a-b).map(md=>interp(st,md)); if(bha.totalLength<depth)throw Error('The string must cover bit MD (add drill pipe)');let mode=settings.mode||'pooh';if(!['pooh','rih','static'].includes(mode))throw Error('Unknown operating mode');let sign=mode==='pooh'?1:mode==='rih'?-1:0;let result=[{md:depth,axial:finite(settings.bitForce||0,'bit force'),normal:0,drag:0,component:elementAtBottomDistance(bha,0).name}];let T=result[0].axial,dragSum=0,normalSum=0;
for(let i=st.length-1;i>0;i--){let up=st[i-1],dn=st[i],ds=dn.md-up.md,mid=interp(st,(up.md+dn.md)/2);let el=elementAtBottomDistance(bha,depth-mid.md),w=el.mass*G*(1-mud/rho),inc=mid.inc*R,beta=Math.abs(dn.dls)*R/30*ds;
let normal=Math.abs(w*Math.sin(inc)*ds)+Math.abs(T)*beta;let friction=mu*normal;let grav=w*Math.cos(inc)*ds;T+=grav+sign*friction;dragSum+=friction;normalSum+=normal;result.push({md:up.md,axial:T,normal,drag:friction,component:el.name});}
result.reverse();return {stringTopAxialForce:result[0].axial,hookload:result[0].axial,normal:normalSum,drag:dragSum,rows:result,mode,assumptions:'Segmented soft-string; buoyed weight, inclination and curvature; excludes stiffness, bending, buckling, motor torque and viscous torque.'};}
function parseCSV(text){const C=globalThis.WellCore||(typeof require==='function'?require('./core.js'):null);const delimiter=text.split(/\r?\n/)[0].includes(';')?';':',';const rows=C.csv(text,delimiter);if(rows.length<2)throw Error('CSV requires at least two survey stations');return rows.map((r,i)=>{const normalized=Object.fromEntries(Object.entries(r).map(([k,v])=>[k.toLowerCase().trim(),v]));return {md:finite(normalized.md,'MD row '+i),inc:finite(normalized.inc??normalized.inclination,'INC row '+i),azi:finite(normalized.azi??normalized.azimuth,'AZI row '+i)};});}
return {survey,interp,dist3,closestOnPolyline,anticollision,normalizeBha,td,parseCSV};
});
