/* Original workflow descriptions. Source documents are not distributed. */
(function (root) {
  const externalFields = [
    "md_m",
    "quantity",
    "value",
    "unit",
    "model_name",
    "model_revision",
  ];
  const item = (
    id,
    title,
    group,
    phase,
    processor,
    purpose,
    requirements,
    outputs,
    limitation,
    fields,
    sample,
    plot,
  ) => ({
    id,
    title,
    group,
    phase,
    processor,
    purpose,
    requirements,
    outputs,
    limitation,
    fields,
    sample,
    plot,
  });
  root.StudyCatalog = [
    item(
      "directional",
      "Directional run review",
      "Directional",
      "Post-well",
      "directional",
      "Understand how observed build and turn change across stable run segments.",
      [
        "Actual surveys and common MD reference",
        "Run/BHA identity and source",
        "Segment boundaries; WOB, toolface and formation context",
      ],
      ["Observed BUR / TUR per segment", "Linked interval and source trace"],
      "Survey descriptors only. No predicted BHA response, bit walk or inverse overgauge.",
      [
        "segment",
        "from_md_m",
        "to_md_m",
        "inc_from_deg",
        "inc_to_deg",
        "azi_from_deg",
        "azi_to_deg",
      ],
      [
        ["Build", 1000, 1030, 20, 23, 359, 1],
        ["Hold", 1030, 1060, 23, 23, 1, 1],
      ],
      "observed_bur_deg_30m",
    ),
    item(
      "mse",
      "Mechanical specific energy",
      "Performance",
      "Post-well",
      "mse",
      "Compare drilling energy and depth of cut over a bit run.",
      [
        "Bit diameter, WOB, torque, RPM and ROP",
        "Explicit bit or surface measurement basis",
        "Source, units and QC review",
      ],
      [
        "MSE with axial and rotational contributions",
        "Depth of cut and drilling strength",
      ],
      "Surface inputs produce a surface proxy. No inferred bit torque, automatic dysfunction diagnosis or default efficiency threshold.",
      ["md_m", "bit_diameter_m", "wob_kN", "torque_kNm", "rpm", "rop_m_h"],
      [
        [1000, 0.216, 80, 3, 120, 20],
        [1030, 0.216, 85, 3.2, 120, 25],
        [1060, 0.216, 90, 3.5, 130, 22],
      ],
      "mse_MPa",
    ),
    item(
      "operations",
      "Operations follow-up",
      "Operations",
      "Execution",
      "operations",
      "Compare source-matched field observations with the planning baseline.",
      [
        "Matching depth, operation and sensor zero",
        "PUW, SOW and FRW; measured/planned SPP and ECD",
        "Source record and QC",
      ],
      ["Pickup and slackoff differences", "SPP and ECD residuals against plan"],
      "Rows must share the declared measurement basis. Differences alone do not diagnose hole cleaning or stuck pipe.",
      [
        "md_m",
        "puw_kN",
        "sow_kN",
        "frw_kN",
        "spp_measured_bar",
        "spp_planned_bar",
        "ecd_measured_kg_m3",
        "ecd_planned_kg_m3",
      ],
      [
        [1000, 1500, 1300, 1400, 230, 225, 1285, 1300],
        [1100, 1550, 1310, 1420, 242, 230, 1290, 1300],
      ],
      "pickup_slackoff_spread_kN",
    ),
    item(
      "hydraulics",
      "Hydraulic observation review",
      "Operations",
      "Execution",
      "hydraulics",
      "Reconcile supplied annular pressure loss with hydrostatic pressure and ECD.",
      [
        "TVD and mud density",
        "Measured or externally calculated annular loss",
        "Source and pressure basis",
      ],
      ["Hydrostatic pressure", "Equivalent circulating density"],
      "Not a rheology or pressure-loss solver. Do not substitute standpipe pressure for annular loss.",
      ["md_m", "tvd_m", "mud_density_kg_m3", "annular_loss_bar"],
      [
        [1000, 950, 1200, 10],
        [2000, 1750, 1200, 18],
      ],
      "ecd_kg_m3",
    ),
    item(
      "jar",
      "Jar pressure-area review",
      "String integrity",
      "Planning",
      "pressureArea",
      "Keep effective axial force distinct from pipe-wall force when reviewing supplied pressure profiles.",
      [
        "Effective axial force, tension positive",
        "Internal/external pressure at each MD",
        "Pipe OD/ID and documented source",
      ],
      [
        "Pressure-area contribution",
        "Wall and effective axial force with sign",
      ],
      "Algebraic pressure-area conversion only. No firing envelope, jar recommendation or coupled hydraulic/contact solver.",
      [
        "md_m",
        "od_mm",
        "id_mm",
        "internal_pressure_bar",
        "external_pressure_bar",
        "effective_axial_kN",
      ],
      [
        [1000, 127, 108, 150, 120, 50],
        [1500, 127, 108, 220, 180, -5],
      ],
      "wall_axial_kN",
    ),
    item(
      "friction",
      "Axial friction sensitivity",
      "String integrity",
      "Planning",
      "sensitivity",
      "Compare declared friction assumptions at selected bit depths using the current string and trajectory.",
      [
        "Current reference surveys and full string",
        "Mud/steel density and casing shoe",
        "Explicit depths and open-hole coefficients",
      ],
      [
        "Pickup, slackoff and static screening matrix",
        "Reproducible assumption cases",
      ],
      "Preliminary axial soft-string approximation. No surface rig tare, torsional torque, buckling or automatic friction fit.",
      [],
      [],
      "pickup_kN",
    ),
    item(
      "standoff",
      "Casing standoff geometry",
      "Well integrity",
      "Planning",
      "standoff",
      "Translate measured or supplied eccentricity into minimum gap and standoff.",
      [
        "Hole diameter and casing OD",
        "Eccentricity at each depth",
        "Measurement or external-model source",
      ],
      ["Minimum radial gap", "Standoff ratio against concentric clearance"],
      "Geometry only. No centralizer spring-force model, beam deformation or cement barrier qualification.",
      ["md_m", "hole_diameter_mm", "casing_od_mm", "eccentricity_mm"],
      [
        [1000, 311, 244, 10],
        [1030, 311, 244, 20],
        [1060, 320, 244, 15],
      ],
      "standoff_percent",
    ),
    item(
      "wear",
      "Measured casing wear",
      "Well integrity",
      "Post-well",
      "wear",
      "Keep measured remaining wall and nominal/minimum-wall denominators explicit.",
      [
        "QC-reviewed wall measurements",
        "Original nominal and minimum wall",
        "Caliper processing method and excluded/noisy intervals",
      ],
      [
        "Remaining wall and nominal loss",
        "Loss using nominal and minimum-wall bases",
      ],
      "No groove reconstruction, calibrated wear prediction or residual pressure rating. Exclude ambiguous coupling/noise intervals before calculation.",
      [
        "md_m",
        "nominal_wall_mm",
        "minimum_original_wall_mm",
        "measured_wall_mm",
      ],
      [
        [1000, 12, 10.5, 11.5],
        [1030, 12, 10.5, 10.2],
        [1060, 12, 10.5, 11],
      ],
      "loss_percent_nominal",
    ),
    item(
      "survey",
      "Plan / actual reconciliation",
      "Well placement",
      "Execution",
      "surveyComparison",
      "Measure coordinate residuals at explicitly matched MD stations.",
      [
        "Plan and actual coordinates at the same MD",
        "Same coordinate/vertical/north reference",
        "Source and survey QC",
      ],
      [
        "North, east and TVD residuals",
        "Horizontal and spatial residual magnitude",
      ],
      "No implicit interpolation or coordinate transform. Residuals are not survey uncertainty or separation factors.",
      [
        "md_m",
        "plan_n_m",
        "plan_e_m",
        "plan_tvd_m",
        "actual_n_m",
        "actual_e_m",
        "actual_tvd_m",
      ],
      [
        [1000, 200, 100, 950, 203, 104, 951],
        [1500, 550, 260, 1250, 557, 263, 1254],
      ],
      "spatial_residual_m",
    ),
    ...[
      [
        "prebha",
        "BHA directional pre-analysis",
        "Directional",
        "Planning",
        "Compare independently calculated bit/BHA design cases.",
        "Bit geometry and steerability; stabilizer gauges/positions; geology/UCS; WOB, toolface and activation",
        "No bit-rock equilibrium solver.",
      ],
      [
        "modal",
        "Vibration and modal study",
        "Performance",
        "Planning",
        "Review sourced mode shapes, frequencies and operating envelopes.",
        "BHA stiffness/mass; contact and boundary conditions; damping; measured high-rate channels",
        "No natural-frequency or critical-speed solver. Use the Dynamics page for measured spectra.",
      ],
      [
        "fatigue",
        "Stress and fatigue study",
        "String integrity",
        "Post-well",
        "Review stress histories and externally assessed damage by component.",
        "Material/connection data; load cycles; S–N method; inspection history",
        "No validated stress or cumulative-fatigue solver.",
      ],
      [
        "completion",
        "Completion running study",
        "Well integrity",
        "Planning",
        "Compare sourced run-in cases by string design, depth and friction assumption.",
        "Completion tally; trajectory/tortuosity; fluid; centralizers; operation and external loads",
        "No lockup or contact-force prediction.",
      ],
      [
        "sag",
        "Sag and local dogleg review",
        "Well placement",
        "Post-well",
        "Reconcile source survey corrections and high-resolution well geometry.",
        "Measurement sensor position; BHA; continuous surveys; source model/revision",
        "No sag correction or inferred micro-dogleg solver.",
      ],
      [
        "casing",
        "Casing load-case register",
        "Well integrity",
        "Planning",
        "Keep casing design cases, loads and source ratings traceable.",
        "Casing tally; material ratings; pressure/temperature; load case; design factors",
        "No API casing rating or triaxial solver.",
      ],
      [
        "dysfunction",
        "Drilling dysfunction review",
        "Performance",
        "Post-well",
        "Keep observed symptoms, formation context and external interpretations distinct.",
        "Source MSE/ROP/WOB/torque/RPM; lithology; vibrations; bit dull grading",
        "No patented diagnostic classifier or causal inference.",
      ],
    ].map(([id, title, group, phase, purpose, req, limit]) =>
      item(
        id,
        title,
        group,
        phase,
        "external",
        purpose,
        [req, "External model name, revision and QC-reviewed result source"],
        [
          "Traceable external result table",
          "Study report and comparison record",
        ],
        limit,
        externalFields,
        [
          [
            1000,
            "Example quantity",
            1,
            "declared unit",
            "External example",
            "1",
          ],
        ],
        "value",
      ),
    ),
  ];
})(globalThis);
